### ISSUE TITLE
system consistency

### ISSUE THREAD

**Issue by jpjarnoux** [padlocbio/padloc-db#9]
Hi
I noticed on multiple system that the number of minimum core gene is greater than the size of the core gene list. So my question is there is a reason, it's a bug, or nothing is impacted. Because if I understand good, those systems will be undetectable. I will give you the example of cbass_type_III, which is with 3 core genes and a minimum_core=4. In that case, the condition minimum core will never be respected.

The list of systems with similar problem:
- cbass_type_III
- cas_type_V
- cas_type_VI
- cas_adaptation
- cbass_type_IV

Thanks

**Comment by leightonpayne** [comment]
This should be fixed with [v2.0.0](https://github.com/padlocbio/padloc-db/releases/tag/v2.0.0)

**Comment by jpjarnoux** [comment]
Hi !
I would like to reopen this issue, because the problem was not fixed for 'cas_adaption'.

**Comment by JacksonLab** [comment]
Hi,

Thanks for the comment. Based on your earlier helpful feedback, Leighton built an in-house QC tool to catch any inconsistencies in the system definition gene counts etc. In this case, the core gene list contains "cas_adaptation", which is a secondary gene assignment [secondary.name] shortcut that links back to >2 entries for [protein.name] in the hmm_meta.txt lookup table. I.e. internally, PADLOC expands "cas_adaptation" to include all genes with "cas_adaptation" listed in [secondary.name]. The [secondary.name] field is a helpful way to add groups of proteins (e.g. Cas effectors proteins) without having to list every protein in each required sys.def (which would also introduce more chance for errors). 

Cheers,

Simon

**Comment by jpjarnoux** [comment]
Hi,
Thank you for your prompt reply.
I understand better how it all works. It is indeed an elegant solution that makes the systems easier to read. Perhaps a keyword or a comment on the systems that present this inconsistency, which in reality isn't one, would make them even easier to read. For the moment, I've only detected this system, but in the future there could be others.
Thanks again
Jérôme.
